import { createServerFn } from "@tanstack/react-start";

export const savePortfolioData = createServerFn({ method: "POST" })
  .inputValidator(
    (d: {
      heroContent: Record<string, unknown>;
      aboutContent: Record<string, unknown>;
      projectsData: Record<string, unknown>[];
      skillGroupsData: Record<string, unknown>[];
      timelineItemsData: Record<string, unknown>[];
    }) => d,
  )
  .handler(async ({ data }) => {
    try {
      const fs = await import("fs/promises");
      const path = await import("path");

      const fileContent = `// This file is auto-generated by the local editor. Do not edit manually unless you know what you are doing.

export const heroContent = ${JSON.stringify(data.heroContent, null, 2)};

export const aboutContent = ${JSON.stringify(data.aboutContent, null, 2)};

export const projectsData = ${JSON.stringify(data.projectsData, null, 2)};

export const skillGroupsData = ${JSON.stringify(data.skillGroupsData, null, 2)};

export const timelineItemsData = ${JSON.stringify(data.timelineItemsData, null, 2)};
`;

      const filePath = path.resolve(process.cwd(), "src/data/portfolio.ts");
      await fs.writeFile(filePath, fileContent, "utf-8");
      return { ok: true };
    } catch (error) {
      console.error("[Editor Server Function] Save failed:", error);
      throw new Error("Failed to write portfolio data to disk");
    }
  });

export const uploadPhoto = createServerFn({ method: "POST" })
  .inputValidator(
    (d: {
      base64: string;
      fileName: string;
    }) => d,
  )
  .handler(async ({ data }) => {
    try {
      const fs = await import("fs/promises");
      const path = await import("path");

      // Decode base64 string to buffer
      const base64Data = data.base64.replace(/^data:image\/\w+;base64,/, "");
      const buffer = Buffer.from(base64Data, "base64");
      
      // Determine file path in the public directory
      const cleanFileName = data.fileName.replace(/[^a-zA-Z0-9.\-_]/g, "_");
      const filePath = path.resolve(process.cwd(), "public", cleanFileName);
      
      // Save file
      await fs.writeFile(filePath, buffer);
      
      return { ok: true, url: `/${cleanFileName}` };
    } catch (error) {
      console.error("[Editor Server Function] Upload failed:", error);
      throw new Error("Failed to write uploaded image to disk");
    }
  });
