import { createServerFn } from "@tanstack/react-start";
import * as fs from "fs/promises";
import * as path from "path";

export const savePortfolioData = createServerFn({ method: "POST" })
  .inputValidator(
    (d: {
      heroContent: Record<string, unknown>;
      aboutContent: Record<string, unknown>;
      projectsData: Record<string, unknown>[];
      skillGroupsData: Record<string, unknown>[];
      timelineItemsData: Record<string, unknown>[];
    }) => d,
  )
  .handler(async ({ data }) => {
    try {
      const fileContent = `// This file is auto-generated by the local editor. Do not edit manually unless you know what you are doing.

export const heroContent = ${JSON.stringify(data.heroContent, null, 2)};

export const aboutContent = ${JSON.stringify(data.aboutContent, null, 2)};

export const projectsData = ${JSON.stringify(data.projectsData, null, 2)};

export const skillGroupsData = ${JSON.stringify(data.skillGroupsData, null, 2)};

export const timelineItemsData = ${JSON.stringify(data.timelineItemsData, null, 2)};
`;

      const filePath = path.resolve(process.cwd(), "src/data/portfolio.ts");
      await fs.writeFile(filePath, fileContent, "utf-8");
      return { ok: true };
    } catch (error) {
      console.error("[Editor Server Function] Save failed:", error);
      throw new Error("Failed to write portfolio data to disk");
    }
  });
