// This file is auto-generated by the local editor. Do not edit manually unless you know what you are doing.

export const heroContent = {
  "headline1": "AI Engineer",
  "headline2": "& Software Developer",
  "tagline": "Hi, I'm Aditya Tayal — a AI/ML enthusiast and Full-Stack Developer passionate about building intelligent applications that solve real-world problems. I enjoy combining machine learning, modern web technologies, and clean software engineering to create scalable products with meaningful impact.",
  "available": true,
  "email": "adityatayal2610@gmail.com",
  "github": "https://github.com/Aditya1026-05",
  "linkedin": "https://www.linkedin.com/in/aditya0898/",
  "open_for_internships": true,
  "open_for_full_time": true,
  "leetcode": "Leetcode.com/Aditya1026_",
  "resume_url": "https://drive.google.com/file/d/1dN1cIkVu2h1xbuyNfYvQrmz4uAiWWPc0/view?usp=sharing"
};

export const aboutContent = {
  "heading": "About Me",
  "initials": "ADITYA",
  "handle": "Aditya2610_",
  "location": "Based in India · Available globally",
  "paragraph1": "I develop AI-powered applications that bridge research and real-world usability. Whether it's training machine learning models, integrating LLMs through Retrieval-Augmented Generation (RAG), Tool Calling or deploying production-ready APIs, I enjoy building intelligent systems that create measurable value.",
  "paragraph2": "Currently pursuing a B.Tech in Electronics & Communication Engineering at Thapar Institute of Engineering & Technology, I'm continuously expanding my expertise in artificial intelligence, software engineering, and system design. I'm passionate about learning, building impactful products, and contributing to teams that solve meaningful engineering challenges."
};

export const projectsData = [
  {
    "id": "a9333097-a3dd-448b-a6dc-e15a5287ca36",
    "title": "NextRound – AI-Powered Mock Interview Platform",
    "tagline": "Resume-aware AI interview platform with adaptive mock interviews",
    "description": "• Architected and developed an MVP of an AI-powered mock interview platform supporting Backend, Frontend, Full Stack, AI/ML, Behavioral, System Design, and Coding interviews.\n\n• Built a resume-aware interview engine that generates adaptive interview blueprints, conducts stateful multi-turn conversations, and asks context-aware follow-up questions based on candidate responses.\n\n• Designed a provider-agnostic LLM orchestration layer with configurable workload profiles, structured prompt management, automatic retry/fallback across Gemini, Groq, and Mistral, and centralized observability.\n\n• Integrated Judge0 to support interactive coding interviews with secure code execution, hidden test cases, and AI-driven discussions on solution approach, time and space complexity, edge cases, and optimizations.\n\n• Currently expanding the platform with Redis-powered conversation memory, WebSockets for real-time communication, voice interviews (STT/TTS), automated interview evaluation, and personalized learning roadmap generation.",
    "tech": [
      "FastAPI",
      "React",
      "TypeScript",
      "PostgreSQL",
      "SQLAlchemy",
      "Alembic",
      "LiteLLM",
      "Judge0",
      "Gemini API",
      "Groq API",
      "Mistral API",
      "JWT Authentication"
    ],
    "year": "2026",
    "sort_order": 10,
    "featured": true,
    "live_url": "",
    "github_url": "https://github.com/Aditya1026-05/NextRound---AI-mock-interview-platform",
    "is_ongoing": true
  },
  {
    "id": "6e613f08-7b3e-4f51-81b8-46fedd4a3710",
    "title": "AI-Powered Poultry Farm Management",
    "tagline": "End-to-end SaaS for modern farms",
    "description": "A full-stack platform with revenue analytics, admin dashboards, an AI assistant, JWT auth, SMTP notifications, and CSV export. Built for scale and deployed to production.",
    "tech": [
      "React",
      "FastAPI",
      "MongoDB",
      "JWT",
      "Render",
      "Gemini API",
      "Tool Calling"
    ],
    "year": "2026",
    "sort_order": 20,
    "featured": true,
    "live_url": "star-poultry-frontend.onrender.com",
    "github_url": "https://github.com/Aditya1026-05/poultry",
    "is_ongoing": false
  },
  {
    "id": "32494482-b3bc-4187-ab8b-7ba4081fd416",
    "title": "Diabetic Foot Ulcer Early Detection",
    "tagline": "Multi-modal deep learning for healthcare - Capstone Project",
    "description": "A CNN-based system for early detection of diabetic foot ulcers using medical imaging and multi-modal AI for clinical support.",
    "tech": [
      "CNN",
      "Deep Learning",
      "Medical Imaging",
      "Multi-modal AI"
    ],
    "year": "2024",
    "sort_order": 30,
    "featured": true,
    "live_url": "",
    "github_url": "",
    "is_ongoing": true
  },
  {
    "id": "3321e202-3669-4a14-a5bb-bce4c9418a57",
    "title": "Hisaab Kitaab Online",
    "tagline": "A Simple expense tracker for students ",
    "description": "built and Deployed ",
    "tech": [
      "Flask",
      "Python",
      "Tailwind css",
      "Render"
    ],
    "year": "2025",
    "sort_order": 40,
    "featured": false,
    "live_url": "hisaabkitaabonline.online/",
    "github_url": "https://github.com/Aditya1026-05/hisaabkitaabonline-expense-tracker-",
    "is_ongoing": false
  },
  {
    "id": "ced701dd-7a11-4619-b56b-5632b135e7c7",
    "title": "Customer Churn Prediction",
    "tagline": "ML pipeline with Streamlit deployment",
    "description": "Predictive modeling with XGBoost and Random Forest, class balancing via SMOTEENN, wrapped in an interactive Streamlit interface.",
    "tech": [
      "Python",
      "XGBoost",
      "Random Forest",
      "Streamlit",
      "SMOTEENN"
    ],
    "year": "2025",
    "sort_order": 50,
    "featured": false,
    "live_url": "",
    "github_url": "https://github.com",
    "is_ongoing": false
  }
];

export const skillGroupsData = [
  {
    "id": "1ec4180c-9841-4e68-b982-1625af4e80a4",
    "title": "Backend",
    "items": [
      "FastAPI",
      "Flask",
      "Django",
      "Node.js",
      "REST APIs",
      "SQLAlchemy",
      "Alembic",
      "JWT Authentication",
      "PostgreSQL",
      "MongoDB",
      "MySQL",
      "SQLite",
      "pgvector",
      "AsyncIO",
      "SMTP",
      "Judge0"
    ],
    "sort_order": 10
  },
  {
    "id": "7efeaded-0de1-4233-8a13-0746883aab63",
    "title": "AI / ML",
    "items": [
      "Machine Learning",
      "Deep Learning",
      "TensorFlow",
      "Keras",
      "Scikit-learn",
      "OpenCV",
      "NumPy",
      "Matplotlib",
      "RAG",
      "LiteLLM",
      "Prompt Engineering",
      "Tool Calling",
      "Gemini API",
      "Groq API"
    ],
    "sort_order": 20
  },
  {
    "id": "7dfccc24-de83-4f86-a820-581ed7472ea5",
    "title": "Languages",
    "items": [
      "Python",
      "C++",
      "SQL",
      "JavaScript",
      "TypeScript"
    ],
    "sort_order": 30
  },
  {
    "id": "06bfe7e8-962a-48c8-8b88-b99f97bc23ce",
    "title": "Tools",
    "items": [
      "Git",
      "GitHub",
      "VS Code",
      "Render",
      "Vercel",
      "GitHub Actions",
      "Postman",
      "Google Colab",
      "Jupyter Notebook"
    ],
    "sort_order": 40
  }
];

export const timelineItemsData = [
  {
    "id": "7841e36d-cd8f-4b0a-9261-782bb8bf052e",
    "year": "2023 — Present",
    "title": "B.Tech, Electronics & Communication",
    "org": "Thapar Institute of Engineering and Technology",
    "description": "",
    "sort_order": 20,
    "cgpa": "7.5",
    "sgpa": "8.76",
    "certificate_url": ""
  },
  {
    "id": "01ab9526-8972-4888-99be-ed7533f86b9a",
    "year": "Jun 2025 - July 2025",
    "title": "Summer Intern",
    "org": "Experiential Learning Centre, Thapar University",
    "description": "Development of thin film gas sensor for detection of acetone in air",
    "sort_order": 30,
    "cgpa": "",
    "sgpa": "",
    "certificate_url": "https://drive.google.com/file/d/1au-V6WhX1Kdi8bibScCSCks6R5Jpd47K/view?usp=sharing"
  },
  {
    "id": "3f8a07cf-2161-44f5-9b4c-1db810bc64b5",
    "year": "Jun 2026 - Present",
    "title": "Summer Intern",
    "org": "Vamcor Technologies Pvt. Ltd",
    "description": "Building and Testing a fully secure Broiler Farm management system with Two ai Bots one based on RAG and one Based on data retrieval from current database(PostgreSQL) ",
    "sort_order": 40,
    "cgpa": "",
    "sgpa": "",
    "certificate_url": ""
  }
];
