// This file is auto-generated by the local editor. Do not edit manually unless you know what you are doing.

export const heroContent = {
  "headline1": "AI Engineer",
  "headline2": "& Full Stack Developer",
  "tagline": "Hi, I'm Aditya Tayal — a AI/ML enthusiast and Full-Stack Developer passionate about building intelligent applications that solve real-world problems. I enjoy combining machine learning, modern web technologies, and clean software engineering to create scalable products with meaningful impact.",
  "available": true,
  "email": "adityatayal2610@gmail.com",
  "github": "https://github.com/Aditya1026-05",
  "linkedin": "https://www.linkedin.com/in/aditya0898/"
};

export const aboutContent = {
  "heading": "About Me",
  "initials": "ADITYA",
  "handle": "Aditya2610_",
  "location": "Based in India · Available globally",
  "paragraph1": "I develop AI-powered applications that bridge research and real-world usability. Whether it's training machine learning models, integrating LLMs through Retrieval-Augmented Generation (RAG), Tool Calling or deploying production-ready APIs, I enjoy building intelligent systems that create measurable value.",
  "paragraph2": "Currently pursuing a B.Tech in Electronics & Communication Engineering at Thapar Institute of Engineering & Technology, I'm continuously expanding my expertise in artificial intelligence, software engineering, and system design. I'm passionate about learning, building impactful products, and contributing to teams that solve meaningful engineering challenges."
};

export const projectsData = [
  {
    "id": "6e613f08-7b3e-4f51-81b8-46fedd4a3710",
    "title": "AI-Powered Poultry Farm Management",
    "tagline": "End-to-end SaaS for modern farms",
    "description": "A full-stack platform with revenue analytics, admin dashboards, an AI assistant, JWT auth, SMTP notifications, and CSV export. Built for scale and deployed to production.",
    "tech": [
      "React",
      "FastAPI",
      "MongoDB",
      "JWT",
      "Render",
      "Gemini API",
      "Tool Calling"
    ],
    "year": "2026",
    "sort_order": 10,
    "featured": true,
    "live_url": "star-poultry-frontend.onrender.com",
    "github_url": "https://github.com/Aditya1026-05/poultry",
    "is_ongoing": true
  },
  {
    "id": "32494482-b3bc-4187-ab8b-7ba4081fd416",
    "title": "Diabetic Foot Ulcer Early Detection",
    "tagline": "Multi-modal deep learning for healthcare",
    "description": "A CNN-based system for early detection of diabetic foot ulcers using medical imaging and multi-modal AI for clinical support.",
    "tech": [
      "CNN",
      "Deep Learning",
      "Medical Imaging",
      "Multi-modal AI"
    ],
    "year": "2024",
    "sort_order": 20,
    "featured": false,
    "live_url": "",
    "github_url": "",
    "is_ongoing": false
  },
  {
    "id": "3321e202-3669-4a14-a5bb-bce4c9418a57",
    "title": "Hisaab Kitaab Online",
    "tagline": "A Simple expense tracker for students ",
    "description": "built and Deployed ",
    "tech": [
      "Flask",
      "Python",
      "Tailwind css",
      "Render"
    ],
    "year": "2025",
    "sort_order": 30,
    "featured": false,
    "live_url": "hisaabkitaabonline.online/",
    "github_url": "https://github.com/Aditya1026-05/hisaabkitaabonline-expense-tracker-",
    "is_ongoing": false
  },
  {
    "id": "ced701dd-7a11-4619-b56b-5632b135e7c7",
    "title": "Customer Churn Prediction",
    "tagline": "ML pipeline with Streamlit deployment",
    "description": "Predictive modeling with XGBoost and Random Forest, class balancing via SMOTEENN, wrapped in an interactive Streamlit interface.",
    "tech": [
      "Python",
      "XGBoost",
      "Random Forest",
      "Streamlit",
      "SMOTEENN"
    ],
    "year": "2024",
    "sort_order": 40,
    "featured": false,
    "live_url": "",
    "github_url": "https://github.com",
    "is_ongoing": false
  }
];

export const skillGroupsData = [
  {
    "id": "7efeaded-0de1-4233-8a13-0746883aab63",
    "title": "AI / ML",
    "items": [
      "Machine Learning",
      "Deep Learning",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "numpy",
      "Opencv",
      "Tensorflow",
      "LLMs",
      "Gemini API",
      "Groq API"
    ],
    "sort_order": 5
  },
  {
    "id": "f40cf988-e6a0-4808-8aa1-1234284b3f68",
    "title": "Languages",
    "items": [
      "C++",
      "Python",
      "JavaScript",
      "TypeScript",
      "SQL"
    ],
    "sort_order": 10
  },
  {
    "id": "1ec4180c-9841-4e68-b982-1625af4e80a4",
    "title": "Frontend",
    "items": [
      "React",
      "TypeScript",
      "Tailwind CSS"
    ],
    "sort_order": 20
  },
  {
    "id": "7dfccc24-de83-4f86-a820-581ed7472ea5",
    "title": "Backend",
    "items": [
      "Node.js",
      "FastAPI",
      "MongoDB",
      "MySQL",
      "SQLite",
      "REST API",
      "JWT",
      "SMTP",
      "pgvector"
    ],
    "sort_order": 30
  },
  {
    "id": "06bfe7e8-962a-48c8-8b88-b99f97bc23ce",
    "title": "Tools",
    "items": [
      "Git",
      "GitHub",
      "Vs Code",
      "Render",
      "Vercel",
      "Github Actions"
    ],
    "sort_order": 50
  }
];

export const timelineItemsData = [
  {
    "id": "7841e36d-cd8f-4b0a-9261-782bb8bf052e",
    "year": "2023 — Present",
    "title": "B.Tech, Electronics & Communication",
    "org": "Thapar Institute of Engineering and Technology",
    "description": "",
    "sort_order": 20,
    "cgpa": "7.44",
    "sgpa": "8.76"
  },
  {
    "id": "01ab9526-8972-4888-99be-ed7533f86b9a",
    "year": "Jun 2025 - July 2025",
    "title": "Summer Intern",
    "org": "Experiential Learning Centre, Thapar University",
    "description": "Development of thin film gas sensor for detection of acetone in air",
    "sort_order": 30,
    "cgpa": "",
    "sgpa": "",
    "certificate_url": "https://drive.google.com/file/d/1au-V6WhX1Kdi8bibScCSCks6R5Jpd47K/view?usp=sharing"
  },
  {
    "id": "3f8a07cf-2161-44f5-9b4c-1db810bc64b5",
    "year": "Jun 2026 - Present",
    "title": "Summer Intern",
    "org": "Vamcor Technologies Pvt. Ltd",
    "description": "Building and Testing a fully secure Broiler Farm management system with Two ai Bots one based on RAG and one Based on data retrieval from current database(PostgreSQL) ",
    "sort_order": 40,
    "cgpa": "",
    "sgpa": "",
    "certificate_url": ""
  }
];
